### ISSUE TITLE
How to transfer files from Host to Device

### ISSUE THREAD

**Issue by sishtiaq** [SamsungResearchUK-IoT-Meetup/samsung-tf-lite#1]
The Device is connected to the Host via a serial2usb cable. 
On the Host, I use `screen` to get a terminal on the Device. 
The Tizen `sdb` tool doesn't see (`sdb devices`) the Device, so I can't 'sdb push` files to it. 
I can't ssh (so, no scp) to the Device.
Need to find out how Device Manager can see the Device. 

#4 and #6 will solve this issue. Maintain this as a parent one.

**Comment by nherriot** [comment]
This can be closed. Needs to be verified on machine in Cambridge on Monday.
The new WiKi section has details on how to setup and use the system using SDB.
[WIKI Copy Files ](https://github.com/SamsungResearchUK-IoT-Meetup/samsung-tf-lite/wiki/Copying-Files-To-The-Board)
