### ISSUE TITLE
work out how to record voice

### ISSUE THREAD

**Issue by sishtiaq** [SamsungResearchUK-IoT-Meetup/samsung-tf-lite#12]
a. On the board [Answer: `parecord`]
b. On the watch

**Comment by nherriot** [comment]
The basic issue seems to be with the permissions system. e.g. to set the audio codec to 2-channel recording mode you would echo '0' into the dir:

   $  echo 0 > /sys/class/audio-codec/mode
   $ /sys/class/audio-codec/mode: Permission denied

However as can be seen we get a permission denied problem.
