### ISSUE TITLE
Connect Device and Host via sdb

### ISSUE THREAD

**Issue by sishtiaq** [SamsungResearchUK-IoT-Meetup/samsung-tf-lite#6]
The Tizen sdb tool doesn't see (sdb devices) the Device, so I can't 'sdb push` files to it.
Need to find out how Device Manager can see the Device.

**Comment by nherriot** [comment]
This can be closed. As I can successfully use PUSH, PULL, and SHELL on the device using the WiFi ADB connectivity. 
Documentation is now provided on how to do the details of this on the [WiKi](https://github.com/SamsungResearchUK-IoT-Meetup/samsung-tf-lite/wiki/Copying-Files-To-The-Board)
